### ISSUE TITLE
bitbar-uptime_robot.5m.py: KeyError: 'average_response_time'

### ISSUE THREAD

**Issue by oneofthedamons** [matryer/xbar-plugins#2068]
fao @finnito - 

Here's the traceback:
```
'/Users/damon/Library/Application Support/xbar/plugins/bitbar-uptime_robot.5m.py'
Traceback (most recent call last):
  File "/Users/damon/Library/Application Support/xbar/plugins/bitbar-uptime_robot.5m.py", line 120, in <module>
    main()
  File "/Users/damon/Library/Application Support/xbar/plugins/bitbar-uptime_robot.5m.py", line 23, in main
    outputArray = parseMonitors(response)
  File "/Users/damon/Library/Application Support/xbar/plugins/bitbar-uptime_robot.5m.py", line 80, in parseMonitors
    responseTime = int(float(monitor["average_response_time"]))
KeyError: 'average_response_time'
```

**Comment by sprak3000** [comment]
@oneofthedamons 

Was the plugin working for you and then started giving this error recently? Wondering if the API updated and broke something. Doing some local testing, I'm not seeing any data come back for average response times, but I'm not sure if that is just due to me setting up a monitor for the first time.

Will let my monitor gather some data for a few days and see if anything comes back then. Otherwise, it may just be a broken API.

**Comment by sprak3000** [comment]
@oneofthedamons 

I've patched up the plugin to at least run and display a `?` in place of response time if the key doesn't exist. If the API isn't broken, data should show up. Will continue to monitor my a bit, but I'm still guessing the API is broken in some way.

**Comment by sprak3000** [comment]
@oneofthedamons 

Should have mentioned you may need to grab the latest source from GitHub.

**Comment by sprak3000** [comment]
@oneofthedamons 

After running for a bit, my results are now returning `average_response_tiime` as a field. If you grab the latest source for the plugin, it should now work whether or not your monitor has that field available.

**Comment by oneofthedamons** [comment]
Confirm the same (after running a Refresh All in xbar, for whatever reason a Refresh didn't suffice). Thanks for your help!
